name: Node CI

on: [push]

env:
  IMAGE_NAME: docker.pkg.github.com/navikt/aktivitetsplan/aktivitetsplan
  TZ: Europe/Amsterdam
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      PRINT_PAYLOAD: true

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Create image tag
        run: echo ::set-env name=IMAGE::${IMAGE_NAME}:$(echo ${{ github.ref }} | cut -d '/' -f3).$(date '+%F-%H%M').$(echo $GITHUB_SHA | cut -c1-7) #eks pa tag  gh-actions.2020-01-08-1255.8fa4236
      - run: npm ci
      - run: npm run test
      - run: npm run build

      - name: Build and publish Docker image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker build -t ${IMAGE} .
          docker push ${IMAGE}

      - name: deply q0 fss
        if: github.ref == 'refs/heads/dev'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-fss
          RESOURCE: nais-q-fss.yaml
          VAR: namespace=q0

      - name: deply q1 fss
        if: github.ref == 'refs/heads/dev'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-fss
          RESOURCE: nais-q-fss.yaml
          VAR: namespace=q1

      - name: deply q0 sbs
        if: github.ref == 'refs/heads/dev'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-sbs
          RESOURCE: nais-q-sbs.yaml
          VAR: namespace=q0, urlmiljo=q

      - name: deply q1 sbs
        if: github.ref == 'refs/heads/dev'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-sbs
          RESOURCE: nais-q-sbs.yaml
          VAR: namespace=q1, urlmiljo=q1

      - name: deply prod fss
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-fss
          RESOURCE: nais-fss.yaml

      - name: deply prod sbs
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-sbs
          RESOURCE: nais-sbs.yaml
